// src/codeAnalyzer.js
// AI-powered code analysis to identify testing needs, edge cases, coverage gaps
// Requirement: "Analyze large and complex codebases to identify testing needs"

const { callAI } = require('./aiClient');
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

// ── SYSTEM PROMPT ─────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are a senior QA architect with 15 years experience.
Analyze the given source code and provide a complete testing strategy.

Your analysis must cover exactly these sections:

1. FUNCTION SUMMARY
   List every function/method found and what it does in one line each.

2. TESTING NEEDS
   What must be tested — list the most critical behaviors.

3. POSITIVE TEST CASES
   List 3 positive scenarios with exact input and expected output.

4. NEGATIVE TEST CASES
   List 3 negative scenarios — wrong inputs, missing data, invalid states.

5. EDGE CASES
   List 3 edge cases — boundary values, empty inputs, null values, timeouts.

6. COVERAGE GAPS
   What is currently NOT tested that SHOULD be tested.
   Be specific about what is risky if left untested.

7. RISK RATING
   Rate overall testing risk: LOW / MEDIUM / HIGH
   One sentence explaining why.

Format your response clearly with numbered sections.
Be specific — mention actual function names and parameter names from the code.`;

async function analyzeCode(filePath) {
  // ── Read the file ────────────────────────────────────────────────────────
  const absolutePath = path.resolve(process.cwd(), filePath);

  if (!fs.existsSync(absolutePath)) {
    console.log(chalk.red(`❌ File not found: ${absolutePath}`));
    return;
  }

  const code = fs.readFileSync(absolutePath, 'utf8');
  const fileName = path.basename(filePath);
  const lineCount = code.split('\n').length;

  console.log(chalk.cyan(`\n📂 Analyzing: ${fileName}`));
  console.log(chalk.gray(`   Lines: ${lineCount} | Size: ${code.length} chars`));
  console.log(chalk.yellow('\n🤖 AI is analyzing your code...\n'));

  // ── Send to AI ───────────────────────────────────────────────────────────
  const userMessage = `Analyze this JavaScript file for testing needs:

File: ${fileName}
Code:
${code}`;

  const analysis = await callAI(SYSTEM_PROMPT, userMessage);

  // ── Print results ────────────────────────────────────────────────────────
  console.log(chalk.green(`\n✅ Analysis Complete: ${fileName}`));
  console.log(chalk.gray('═'.repeat(60)));
  console.log(chalk.white(analysis));
  console.log(chalk.gray('═'.repeat(60)));

  // ── Save results to file ─────────────────────────────────────────────────
  const outputDir = path.join(process.cwd(), 'reports', 'code-analysis');
  fs.mkdirSync(outputDir, { recursive: true });

  const outputFile = path.join(outputDir,
    `${fileName.replace('.js', '')}-analysis.md`);

  const markdown = `# Code Analysis: ${fileName}
Generated: ${new Date().toLocaleString()}
Lines: ${lineCount}

---

${analysis}

---
*Generated by AI QA Framework - Code Analyzer*
`;

  fs.writeFileSync(outputFile, markdown);
  console.log(chalk.cyan(`\n💾 Analysis saved to: reports/code-analysis/${fileName.replace('.js','')}-analysis.md`));
}

module.exports = { analyzeCode };